/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "evyykceyssbcwpqvytmn"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2eXlrY2V5c3NiY3dwcXZ5dG1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTc1NjcsImV4cCI6MjA2OTk3MzU2N30.dBRRd-5JLaJfBr3qUa38kMUy-Z44AG6d2I7-gFIipSM"